from enum import StrEnum, auto


class SessionPriceDurables(StrEnum):
    ORDER_SVC_SESSION_PRICES_CREATED_SYNC_DB = auto()
    ORDER_SVC_SESSION_PRICES_BULK_CREATED_SYNC_DB = auto()
    ORDER_SVC_SESSION_PRICES_UPDATED_SYNC_DB = auto()
    ORDER_SVC_SESSION_PRICES_BULK_UPDATED_SYNC_DB = auto()
